set serverout on

--QUESTION1
SELECT DEPARTMENT_ID, 
       LISTAGG (FIRST_NAME || ' ' ||LAST_NAME, ', ') 
       WITHIN GROUP (ORDER BY DEPARTMENT_ID) AS NEWLIST 
FROM HR.EMPLOYEES 
GROUP BY DEPARTMENT_ID;

--QUESTION2
SELECT HR.EMPLOYEES.*, 
	  SUM(SALARY) OVER (PARTITION BY JOB_ID 
					    ORDER BY HIRE_DATE 
      ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) NUM 
FROM HR.EMPLOYEES;

--QUESTION3
SELECT HR.EMPLOYEES.*, 
    ROW_NUMBER() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) NUM 
FROM HR.EMPLOYEES;

--QUESTION4

SELECT HR.EMPLOYEES.*, 
	   ROW_NUMBER() OVER (PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE ASC) NUM 
FROM HR.EMPLOYEES;

--QUESTION5
SELECT HR.EMPLOYEES.FIRST_NAME,HR.EMPLOYEES.LAST_NAME,HR.EMPLOYEES.SALARY, 
	LAG(SALARY,1) OVER (PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE) PREVIOUS_VALUE ,
    LEAD(SALARY,1) OVER (PARTITION BY DEPARTMENT_ID ORDER BY EMPLOYEE_ID) NEXT_VALUE  
FROM HR.EMPLOYEES ORDER BY DEPARTMENT_ID;
