--CALLING THE UNIVERSITY WITH THE NAME OF THE PERSON--

DECLARE 
Input_Name varchar(60):='Ümit';
University varchar(60);
BEGIN
SELECT Universty_Name INTO University FROM Student WHERE First_Name=Input_Name;
DBMS_OUTPUT.PUT_LINE(University);
END;
/

--CALLING THE UNIVERSITY WITH THE NAME OF THE PERSON WITH PARAMETER--

CREATE OR REPLACE PROCEDURE UNIVERSITY_SHOWING(
INPUT_NAME IN VARCHAR)
IS
UNIVERSITY varchar(50);
BEGIN
SELECT Universty_Name INTO UNIVERSITY FROM Student Where First_Name=INPUT_NAME;
DBMS_OUTPUT.PUT_LINE(UNIVERSITY);
END;
/

EXEC UNIVERSITY_SHOWING('Ümit');
