--QUESTION-1--
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MONTHS_BETWEEN(SYSDATE,HIRE_DATE) 
FROM HR.EMPLOYEES;

--QUESTION-2--

SELECT  JOB_ID, DECODE(JOB_ID,'AD_PRES','A',
                             'ST_MAN','B',       
                             'IT_PROG','C',
                             'SA_REP','D',
                             'ST_CLERK','E',
                             '0') "RESULT" FROM HR.JOBS;
                             
--QUESTION-3--

SELECT JOB_ID,CASE JOB_ID WHEN 'AD_PRES' THEN 'A'
                          WHEN 'ST_MAN' THEN 'B'
                          WHEN 'IT_PROG' THEN 'C'
                          WHEN 'SA_REP' THEN 'D'
                          WHEN 'ST_CLERK' THEN 'E'
                 ELSE '0' END "RESULT"
FROM HR.JOBS;

--QUESTION-4--
SELECT DISTINCT E.EMPLOYEE_ID,E.LAST_NAME
FROM HR.EMPLOYEES E INNER JOIN (SELECT DEPARTMENT_ID 
                                FROM HR.EMPLOYEES
                                WHERE LAST_NAME LIKE '%i%') E2 
ON E.DEPARTMENT_ID=E2.DEPARTMENT_ID 
ORDER BY E.EMPLOYEE_ID ASC;

--QUESTION-5--

CREATE TABLE MY_EMPLOYEE_TABLE(
EMP_ID INT,
LAST_NAME VARCHAR(50),
FIRST_NAME VARCHAR(50),
SALARY INT
)
INSERT INTO MY_EMPLOYEE_TABLE(EMP_ID,LAST_NAME,FIRST_NAME,SALARY) VALUES(1,'Black','John',1100);
INSERT INTO MY_EMPLOYEE_TABLE(EMP_ID,LAST_NAME,FIRST_NAME,SALARY) VALUES(2,'White','Kent',1300);
INSERT INTO MY_EMPLOYEE_TABLE(EMP_ID,LAST_NAME,FIRST_NAME,SALARY) VALUES(3,'Orange','David',1700);
INSERT INTO MY_EMPLOYEE_TABLE(EMP_ID,LAST_NAME,FIRST_NAME,SALARY) VALUES(4,'Pink','Alissa',1900);

UPDATE MY_EMPLOYEE_TABLE SET
SALARY=1.10*SALARY;

DELETE MY_EMPLOYEE_TABLE
WHERE FIRST_NAME='David';

TRUNCATE TABLE MY_EMPLOYEE_TABLE;
