CREATE OR REPLACE PROCEDURE GET_NAME(EMP_ID NUMBER)
IS
X VARCHAR(50);
BEGIN
    SELECT FIRST_NAME INTO X FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=EMP_ID;
    DBMS_OUTPUT.PUT_LINE(X);
END;
/

BEGIN
    GET_NAME('100');
END;
/
