CREATE OR REPLACE FUNCTION FUNCTION_PRINT_DAY(INPUT_DATE VARCHAR2) 
RETURN VARCHAR2 
AS 
X VARCHAR2(50);
BEGIN
SELECT TO_CHAR(TO_DATE(INPUT_DATE,'YYYYMMDD'),'DAY') INTO X  FROM DUAL;
RETURN X;
END FUNCTION_PRINT_DAY;

CREATE OR REPLACE PROCEDURE PRINT_DAY(TEMP_DATE  VARCHAR2) IS
    OUTPUT_DAY_NAME VARCHAR(20);
BEGIN
    OUTPUT_DAY_NAME := FUNCTION_PRINT_DAY(TEMP_DATE);
    DBMS_OUTPUT.PUT_LINE(OUTPUT_DAY_NAME);
END;
/

DECLARE
BEGIN
    PRINT_DAY('19960225');
END;
