CREATE OR REPLACE PACKAGE EMP_PACKAGE IS
PROCEDURE FIRST_NAME_EMPLOYEE;
END EMP_PACKAGE;

CREATE OR REPLACE PACKAGE BODY EMP_PACKAGE IS
PROCEDURE FIRST_NAME_EMPLOYEE 
IS
    BEGIN
        FOR X IN (SELECT FIRST_NAME FROM HR.EMPLOYEES)
            LOOP
             DBMS_OUTPUT.PUT_LINE(X.FIRST_NAME);
            END LOOP;
    END;
END EMP_PACKAGE;

BEGIN
    EMP_PACKAGE.FIRST_NAME_EMPLOYEE;
END;
/
